### ISSUE TITLE
Appreciation issue! 

### ISSUE THREAD

**Issue by holmes-py** [root-tanishq/autorev.sh#1]
Nice work! Liked this idea! 
Maybe you can add some error handling so when that script runs, it will move line by line and execute every payload until one of them works, so that even if some box doesn't have python2, but have python3, then it will go over py2 shell, error handle it and then move to py3 shell. 
All in all a nice idea!

**Comment by root-tanishq** [comment]
Thank you I am looking forward to apply the changes and also making a condition if python or python3 exists on the attack machine it will directly give the pty shell
just like the enhanced version of this python pty shells - https://github.com/infodox/python-pty-shells

**Comment by ghost** [comment]
or maybe this little jack off is just a thief hi hjarry remmeber me i bet you do i amn the asshole that found you remember. SO fyi i had the fbi visit me told them about all that happen i still had the hard drives the emails all of it. I have followed you for 3 years you should of noty started with me i told you one day we would get even days is coming hommie watch what ya open and dont ever open a door with out being certain whats on the other side. You still owe me 25.5 btc

**Comment by ghost** [comment]
> Nice work! Liked this idea! Maybe you can add some error handling so when that script runs, it will move line by line and execute every payload until one of them works, so that even if some box doesn't have python2, but have python3, then it will go over py2 shell, error handle it and then move to py3 shell. All in all a nice idea!
or maybe this little jack off is just a thief hi hjarry remmeber me i bet you do i amn the asshole that found you remember. SO fyi i had the fbi visit me told them about all that happen i still had the hard drives the emails all of it. I have followed you for 3 years you should of noty started with me i told you one day we would get even days is coming hommie watch what ya open and dont ever open a door with out being certain whats on the other side. You still owe me 25.5 btc
